"""기초 테이블 세팅

Revision ID: 54ad29016f85
Revises: dae9035a0459
Create Date: 2026-04-24 16:58:45.743889

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54ad29016f85'
down_revision: Union[str, Sequence[str], None] = 'dae9035a0459'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interviewers',
    sa.Column('interviewer_id', sa.Integer(), autoincrement=True, nullable=False, comment='면접관 기본키 id'),
    sa.Column('interviewer_email', sa.String(), nullable=False, comment='면접관 이메일'),
    sa.Column('interviewer_name', sa.String(), nullable=False, comment='면접관 이름'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='생성일. 현재 시간으로 자동 생성'),
    sa.PrimaryKeyConstraint('interviewer_id')
    )
    op.create_table('positions',
    sa.Column('position_id', sa.Integer(), autoincrement=True, nullable=False, comment='직무 테이블 기본키 id'),
    sa.Column('position_name', sa.String(length=100), nullable=False, comment='직무명'),
    sa.Column('department_name', sa.String(length=100), nullable=False, comment='부서명'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='생성일'),
    sa.PrimaryKeyConstraint('position_id')
    )
    op.create_table('candidates',
    sa.Column('candidate_id', sa.Integer(), autoincrement=True, nullable=False, comment='지원자 기본키 id'),
    sa.Column('position_id', sa.Integer(), nullable=True, comment='직무명 (positions 테이블 FK)'),
    sa.Column('name', sa.String(length=50), nullable=True, comment='이름'),
    sa.Column('date_of_birth', sa.Date(), nullable=True, comment='생년월일'),
    sa.Column('gender', sa.String(length=10), nullable=True, comment='성별'),
    sa.Column('address', sa.String(length=255), nullable=True, comment='현주소'),
    sa.Column('phone', sa.String(length=20), nullable=True, comment='휴대폰'),
    sa.Column('email', sa.String(length=255), nullable=True, comment='이메일'),
    sa.Column('application_status', sa.String(length=20), nullable=False, comment='지원단계 (서류, 1차, 2차 등)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='생성일'),
    sa.ForeignKeyConstraint(['position_id'], ['positions.position_id'], ),
    sa.PrimaryKeyConstraint('candidate_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('interview_slots',
    sa.Column('slot_id', sa.Integer(), autoincrement=True, nullable=False, comment='면접 시간 기본키 id'),
    sa.Column('position_id', sa.Integer(), nullable=True, comment='직무 FK (공고/전형 테이블이 생기면 변경 예정)'),
    sa.Column('interview_round', sa.String(length=20), nullable=False, comment='면접 라운드 (1차/2차/3차/최종)'),
    sa.Column('interview_starts_at', sa.DateTime(timezone=True), nullable=False, comment='실제 면접 시작 시간'),
    sa.Column('interview_ends_at', sa.DateTime(timezone=True), nullable=False, comment='실제 면접 종료 시간'),
    sa.Column('booking_deadline_at', sa.DateTime(timezone=True), nullable=True, comment='예약 마감 시각'),
    sa.Column('capacity', sa.Integer(), nullable=False, comment='예약 가능 인원'),
    sa.Column('slot_status', sa.String(length=20), nullable=False, comment='슬롯 상태 (open/full/closed)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='생성일'),
    sa.CheckConstraint("slot_status IN ('open', 'full', 'closed')", name='check_slot_status_valid'),
    sa.CheckConstraint('booking_deadline_at IS NULL OR booking_deadline_at <= interview_starts_at', name='check_booking_deadline_before_start'),
    sa.CheckConstraint('interview_starts_at < interview_ends_at', name='check_interview_time_order'),
    sa.ForeignKeyConstraint(['position_id'], ['positions.position_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('slot_id')
    )
    op.create_table('interview_bookings',
    sa.Column('booking_id', sa.Integer(), autoincrement=True, nullable=False, comment='면접 예약 기본키 id'),
    sa.Column('slot_id', sa.Integer(), nullable=False, comment='예약한 면접 시간 FK'),
    sa.Column('candidate_id', sa.Integer(), nullable=False, comment='예약한 지원자 FK'),
    sa.Column('booking_status', sa.String(length=20), nullable=False, comment='예약 상태 (booked/cancelled)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='예약 확정 시간'),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True, comment='취소 시각'),
    sa.CheckConstraint("(booking_status = 'cancelled' AND cancelled_at IS NOT NULL) OR (booking_status = 'booked' AND cancelled_at IS NULL)", name='check_cancelled_at_consistency'),
    sa.CheckConstraint("booking_status IN ('booked', 'cancelled')", name='check_booking_status_valid'),
    sa.CheckConstraint('cancelled_at IS NULL OR cancelled_at >= created_at', name='check_cancelled_after_created'),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.candidate_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['slot_id'], ['interview_slots.slot_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('booking_id')
    )
    op.create_table('interview_slot_interviewers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='면접관 배정 기본키 id'),
    sa.Column('slot_id', sa.Integer(), nullable=False, comment='배정된 면접 슬롯 FK'),
    sa.Column('interviewer_id', sa.Integer(), nullable=False, comment='배정된 면접관 FK'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='면접관 배정 시각'),
    sa.ForeignKeyConstraint(['interviewer_id'], ['interviewers.interviewer_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['slot_id'], ['interview_slots.slot_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slot_id', 'interviewer_id', name='uq_slot_interviewer')
    )
    op.create_table('questions',
    sa.Column('question_id', sa.Integer(), autoincrement=True, nullable=False, comment='질문 기본키 id'),
    sa.Column('candidate_id', sa.Integer(), nullable=True, comment='지원자 FK (삭제되면 NULL, 질문 데이터는 보존)'),
    sa.Column('position_id', sa.Integer(), nullable=True, comment='직무 FK (직무 기반 질문 생성 시)'),
    sa.Column('question_text', sa.Text(), nullable=False, comment='질문 내용'),
    sa.Column('question_type', sa.String(length=30), nullable=False, comment='질문 유형 (job_based, candidate_based)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='생성일'),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.candidate_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['position_id'], ['positions.position_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('question_id')
    )
    op.create_table('resumes',
    sa.Column('resume_id', sa.Integer(), autoincrement=True, nullable=False, comment='이력서 기본키 id'),
    sa.Column('position_id', sa.Integer(), nullable=False, comment='지원분야 (1지망 직무 FK)'),
    sa.Column('candidate_id', sa.Integer(), nullable=False, comment='지원자 FK'),
    sa.Column('desired_location', sa.String(length=100), nullable=True, comment='희망근무지'),
    sa.Column('second_position_id', sa.Integer(), nullable=True, comment='2지망 직무 FK'),
    sa.Column('desired_salary', sa.Integer(), nullable=True, comment='희망직급/희망연봉'),
    sa.Column('veteran_eligibility', sa.String(length=50), nullable=True, comment='보훈여부 (보훈 번호 작성)'),
    sa.Column('disability', sa.String(length=50), nullable=True, comment='장애여부'),
    sa.Column('file_path', sa.String(length=500), nullable=True, comment='원본 이력서 저장 경로'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='생성일'),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.candidate_id'], ),
    sa.ForeignKeyConstraint(['position_id'], ['positions.position_id'], ),
    sa.ForeignKeyConstraint(['second_position_id'], ['positions.position_id'], ),
    sa.PrimaryKeyConstraint('resume_id')
    )
    op.create_table('educations',
    sa.Column('education_id', sa.Integer(), autoincrement=True, nullable=False, comment='학력사항 테이블 기본키 id'),
    sa.Column('resume_id', sa.Integer(), nullable=False, comment='이력서 FK'),
    sa.Column('school_name', sa.String(length=100), nullable=True, comment='학교명'),
    sa.Column('department', sa.String(length=100), nullable=True, comment='전공'),
    sa.Column('completion_status', sa.String(length=50), nullable=True, comment='학력 구분 (고등학교, 대학교, 대학원 등)'),
    sa.Column('attendance_start_period', sa.Date(), nullable=True, comment='재학기간 시작일'),
    sa.Column('attendance_end_period', sa.Date(), nullable=True, comment='재학기간 종료일'),
    sa.Column('location', sa.String(length=100), nullable=True, comment='소재지'),
    sa.Column('grade', sa.String(length=20), nullable=True, comment='학점'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='생성일'),
    sa.CheckConstraint('attendance_end_period >= attendance_start_period', name='check_attendance_period_valid'),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.resume_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('education_id')
    )
    op.create_table('experiences',
    sa.Column('experience_id', sa.Integer(), autoincrement=True, nullable=False, comment='경력사항 테이블 기본키 id'),
    sa.Column('resume_id', sa.Integer(), nullable=False, comment='이력서 FK'),
    sa.Column('company', sa.String(length=200), nullable=True, comment='회사명'),
    sa.Column('role', sa.String(length=200), nullable=True, comment='근무부서 / 담당업무'),
    sa.Column('job_title', sa.String(length=100), nullable=True, comment='직위'),
    sa.Column('salary', sa.Integer(), nullable=True, comment='연봉 (단위: 원)'),
    sa.Column('reason_for_leaving', sa.String(length=500), nullable=True, comment='퇴직사유'),
    sa.Column('employment_start_period', sa.Date(), nullable=True, comment='근무기간 시작일'),
    sa.Column('employment_end_period', sa.Date(), nullable=True, comment='근무기간 종료일'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='생성일'),
    sa.CheckConstraint('employment_end_period >= employment_start_period', name='check_employment_period_valid'),
    sa.CheckConstraint('salary >= 0', name='check_salary_non_negative'),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.resume_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('experience_id')
    )
    op.create_table('military',
    sa.Column('military_id', sa.Integer(), autoincrement=True, nullable=False, comment='병역사항 테이블 기본키 id'),
    sa.Column('resume_id', sa.Integer(), nullable=False, comment='이력서 FK'),
    sa.Column('military_type', sa.String(length=50), nullable=True, comment='병역구분 (미필, 면제, 복무완료 등)'),
    sa.Column('military_service', sa.String(length=50), nullable=True, comment='군별 (육군, 해군, 공군, 해병대 등)'),
    sa.Column('military_start_period', sa.Date(), nullable=True, comment='복무 기간 시작일'),
    sa.Column('military_end_period', sa.Date(), nullable=True, comment='복무 기간 종료일'),
    sa.Column('military_rank', sa.String(length=50), nullable=True, comment='계급'),
    sa.Column('exemption_reason', sa.String(length=200), nullable=True, comment='면제 사유'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='생성일'),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.resume_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('military_id')
    )
    op.create_table('qualifications',
    sa.Column('qualification_id', sa.Integer(), autoincrement=True, nullable=False, comment='자격사항 테이블 기본키 id'),
    sa.Column('resume_id', sa.Integer(), nullable=False, comment='이력서 FK'),
    sa.Column('certificate', sa.String(length=200), nullable=True, comment='자격증 명'),
    sa.Column('organization', sa.String(length=200), nullable=True, comment='발행처'),
    sa.Column('issue_date', sa.Date(), nullable=True, comment='취득년월'),
    sa.Column('certificate_number', sa.String(length=100), nullable=True, comment='자격인증번호'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='생성일'),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.resume_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('qualification_id')
    )
    op.create_table('statements',
    sa.Column('statement_id', sa.Integer(), autoincrement=True, nullable=False, comment='자기소개서 테이블 기본키 id'),
    sa.Column('resume_id', sa.Integer(), nullable=False, comment='이력서 FK'),
    sa.Column('question', sa.String(length=500), nullable=True, comment='자기소개서 질문'),
    sa.Column('answer', sa.Text(), nullable=True, comment='자기소개서 답변'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='생성일'),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.resume_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('statement_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('statements')
    op.drop_table('qualifications')
    op.drop_table('military')
    op.drop_table('experiences')
    op.drop_table('educations')
    op.drop_table('resumes')
    op.drop_table('questions')
    op.drop_table('interview_slot_interviewers')
    op.drop_table('interview_bookings')
    op.drop_table('interview_slots')
    op.drop_table('candidates')
    op.drop_table('positions')
    op.drop_table('interviewers')
    # ### end Alembic commands ###
