"""질문 테이블 컬럼 추가

Revision ID: b1ed92ca04e1
Revises: 52ca960a5f75
Create Date: 2026-04-29 17:58:51.189581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b1ed92ca04e1'
down_revision: Union[str, Sequence[str], None] = '52ca960a5f75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('evaluation_intent', sa.Text(), nullable=True, comment='Question evaluation intent'))
    op.add_column('questions', sa.Column('generation_basis', sa.Text(), nullable=True, comment='Question generation basis'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'generation_basis')
    op.drop_column('questions', 'evaluation_intent')
    op.create_table('saved_question_sets',
    sa.Column('set_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('interviewer_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('question_ids', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['interviewer_id'], ['interviewers.interviewer_id'], name=op.f('saved_question_sets_interviewer_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['interview_sessions.session_id'], name=op.f('saved_question_sets_session_id_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('set_id', name=op.f('saved_question_sets_pkey'))
    )
    op.create_table('interview_sessions',
    sa.Column('session_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('session_id', name=op.f('interview_sessions_pkey'))
    )
    op.create_table('question_reactions',
    sa.Column('reaction_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('question_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('session_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('reaction', sa.VARCHAR(length=16), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.question_id'], name=op.f('question_reactions_question_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['interview_sessions.session_id'], name=op.f('question_reactions_session_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('reaction_id', name=op.f('question_reactions_pkey')),
    sa.UniqueConstraint('session_id', 'question_id', name=op.f('uq_reaction_session_question'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_question_reactions_session_id'), 'question_reactions', ['session_id'], unique=False)
    op.create_index(op.f('ix_question_reactions_question_id'), 'question_reactions', ['question_id'], unique=False)
    # ### end Alembic commands ###
